// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pdcgo/inventory_service"
	"github.com/pdcgo/shared/configs"
	"github.com/pdcgo/shared/custom_connect"
	"net/http"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	serveMux := http.NewServeMux()
	defaultInterceptor, err := custom_connect.NewDefaultInterceptor()
	if err != nil {
		return nil, err
	}
	appConfig, err := configs.NewProductionConfig()
	if err != nil {
		return nil, err
	}
	db, err := NewDatabase(appConfig)
	if err != nil {
		return nil, err
	}
	projectConfig := NewProjectConfig()
	inventoryPushHandler := inventory_service.NewInventoryPushHandler(db, projectConfig)
	inventoryPushHttpHandler := inventory_service.NewInventoryPushHttpHandler(inventoryPushHandler)
	registerHandler := inventory_service.NewRegister(serveMux, defaultInterceptor, inventoryPushHttpHandler)
	registerReflectFunc := custom_connect.NewRegisterReflect(serveMux)
	app := NewApp(serveMux, registerHandler, registerReflectFunc)
	return app, nil
}
